### ISSUE TITLE
Add Algorithm that you find useful for Interview Preparations

### ISSUE THREAD

**Issue by dheeraj-2000** [dheeraj-2000/dsalgo#1]
### Please make sure the algorithm you're contributing is not already present in the repo.

**Comment by smdp2000** [comment]
Hey @dheeraj-2000 i would like to add code to find Longest Common Subsequence using DP

**Comment by dheeraj-2000** [comment]
Okay go ahead  Assigned to #1 to @smdp2000

**Comment by smdp2000** [comment]
checkout my pr #2

**Comment by smdp2000** [comment]
checkout my pr #3

**Comment by yogesh-kansal** [comment]
i want to work on it issue,pleae assign it to me.

**Comment by ag278** [comment]
@dheeraj-2000  I would like to work on this issue .Please assign this to me

**Comment by dheeraj-2000** [comment]
@ag278 you can send a PR.

**Comment by reethu-annjo** [comment]
I would like to make contributions here:)

**Comment by dheeraj-2000** [comment]
@reethu-annjo checkout READAME of this repo and start contributing.

**Comment by rohanmahto592** [comment]
hey, can I add Kadane algorithm and  Moore voting algorithm

**Comment by dheeraj-2000** [comment]
@rohanmahto592 Yes, Put it in Algorithms folder.

**Comment by rahulpathak-github** [comment]
@dheeraj-2000 Please let me know if I should proceed to add,
1. Algorithm to invert a binary tree
2. Algorithm to find the largest subtree sum in a binary tree

**Comment by dheeraj-2000** [comment]
@rahulpathak-github Yes, put them in _dsalgo/Binary_tree/_ folder. Please mention Time and Space Complexities, also adding some description would be more appreciable.

**Comment by rohanmahto592** [comment]
Already done, but u have'nt merged it.

**Comment by ABHAY2000** [comment]
hey, Can I add CPU Scheduling Algorithm like FCFS, SJF, Priority, etc. in C language ?

**Comment by dheeraj-2000** [comment]
@ABHAY2000 yes, you can create a new folder as **OS Algorithms** or **CPU Scheduling Algorithms** in the repo, and put your algorithms in that.

**Comment by taneemishere** [comment]
Can I add the Stacks Implementation into this repository?

**Comment by dheeraj-2000** [comment]
@taneemishere Yes, but put it in the right folder (if implemented using array then put in **Arrays** folder, or if its using linkedlist then put in **Linked_List** folder)

**Comment by ABHAY2000** [comment]
@dheeraj-2000 Done with OS Algorithms. I have uploaded this folder in Algorithms folder.

**Comment by taneemishere** [comment]
@dheeraj-2000 Okay I'll do it.

**Comment by ankita413** [comment]
Hey @dheeraj-2000 I want to add algorithms for top view,bottom view,left view,righ view and diagonal traversal of Binary tree. ALso I want to add implementation of trie data structure. Pls assign me this. Thankyou

**Comment by dheeraj-2000** [comment]
@ankita413 checkout the guildlines, write the algorithms and send a PR

**Comment by ankita413** [comment]
Ok,Sure

**Comment by Rac-Ro007** [comment]
@dheeraj-2000 , I want to add File Allocation methods of Operating System. Will it be valuable and should i proceed with it??

**Comment by dheeraj-2000** [comment]
@Rac-Ro007 yeah you can contribute, put that at right position in Algorthms folder

**Comment by ankita413** [comment]
hey   @dheeraj-2000 i am trying to push my files to my branch and commit but its giving the following error  
![Screenshot (72)](https://user-images.githubusercontent.com/55186999/96635180-292fe380-1339-11eb-856c-99b41640506a.png)

**Comment by dheeraj-2000** [comment]
Hey @ankita413 as you're pushing from a new branch, so probably your branch is not set-up for remote push, hence you're gettig this error 
Please try to set-up **dev_ankita** branch and then push your changes.

**Comment by ankita413** [comment]
![Screenshot (73)](https://user-images.githubusercontent.com/55186999/96685613-fe767700-139a-11eb-8ca2-d243dd1a3ab1.png)

@dheeraj-2000  well i tried but it doen't seem to work. Can u please share the steps on how to do the entire process. Thanks in advance

**Comment by dheeraj-2000** [comment]
Hey @ankita413 please ping me on [LinkedIn](https://www.linkedin.com/in/dheeraj-2000/).

**Comment by lkbhitesh07** [comment]
Hey, @dheeraj-2000 Just want to ask, I'm planning to upload some important questions to prepare for big tech companies independent of languages. 
So what I'm planning is to simply upload that list of questions and below that making subfolder according to which you can find a solution. As I've solved some questions as I'll solve it I'll add the solutions.
What do you say?

**Comment by dheeraj-2000** [comment]
@lkbhitesh07 Sure, make a new folder as **Interview Preparation** and do your contribution in that.
