### ISSUE TITLE
Longest Common Prefix - String DSA

### ISSUE THREAD

**Issue by jen-sjen** [dheeraj-2000/dsalgo#194]
Hey there, I'm participating in #hactoberfest2k21, Please assign me the issue. Good day!
Write a function to find the longest common prefix string amongst an array of strings.
If there is no common prefix, return an empty string "".
Example:
Input: strs = ["flower","flow","flight"]
Output: "fl"

**Comment by dheeraj-2000** [comment]
Issue resolved
