### ISSUE TITLE
Addition of concept of Disjoint Set Union

### ISSUE THREAD

**Issue by khushbooSingh99** [dheeraj-2000/dsalgo#195]
**Addition of DSU concept.**

Often it is also called Union Find because of its two main operations.

This data structure provides the following capabilities. We are given several elements, each of which is a separate set. A DSU will have an operation to combine any two sets, and it will be able to tell in which set a specific element is. The classical version also introduces a third operation, it can create a set from a new element.

Thus the basic interface of this data structure consists of only three operations:

make_set(v) - creates a new set consisting of the new element v
union_sets(a, b) - merges the two specified sets (the set in which the element a is located, and the set in which the element b is located)
find_set(v) - returns the representative (also called leader) of the set that contains the element v. This representative is an element of its corresponding set. It is selected in each set by the data structure itself (and can change over time, namely after union_sets calls). This representative can be used to check if two elements are part of the same set or not. a and b are exactly in the same set, if find_set(a) == find_set(b). Otherwise they are in different sets.

I will add a question that involves this concept.
I will update the corresponding PR Number asap.
Please accept my improvement. @dheeraj-2000

**Comment by dheeraj-2000** [comment]
Issue resolved
