### ISSUE TITLE
Leet Code: Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by AbhinavRajputEXE** [dheeraj-2000/dsalgo#352]
Hey, I want to implement the solution to this medium-level leet Code problem in JAVA.
My runtime beats the 85%+ submission.
Here is the problem link: https://leetcode.com/problems/longest-substring-without-repeating-characters/

I want to do this as a hacktoberfest contribution
Please assign this to me.

**Comment by Sanketh149** [comment]
I want to do this as a hacktoberfest contribution
Please assign this to me.
