### ISSUE TITLE
Automatically add the contributers images in readme file and make it more beautifull

### ISSUE THREAD

**Issue by Ankurrawat-12** [dheeraj-2000/dsalgo#610]

**Comment by Beast71421** [comment]
Hi @dheeraj-2000 I would like to work on this issue, Can I have it?

**Comment by dheeraj-2000** [comment]
Sure

**Comment by Beast71421** [comment]
thanks can you assign me this issue and add hacktoberfest, hacktoberd=fest-accepted label

**Comment by Beast71421** [comment]
![image](https://user-images.githubusercontent.com/78417225/194753471-a41c0337-eb3f-42d5-8e09-88d6d2217ba2.png)
Done can you check the pr and add the labels
