### ISSUE TITLE
Implementation Primes Number Checker

### ISSUE THREAD

**Issue by iNitialM503** [dheeraj-2000/dsalgo#617]
I want to add primes number sorting list

**Comment by 22tanyabansal** [comment]
hey, I want to contribute in this issue. Please assign this task to me.

**Comment by Kartik213** [comment]
hey, Please assign this task to me.

**Comment by AkanshuAich** [comment]
please assign me the task

**Comment by dheeraj-2000** [comment]
Hi @iNitialM503, you can send a PR linking this issue.
