### ISSUE TITLE
Add hackerrank 30 days of code in c++ language

### ISSUE THREAD

**Issue by ag41-tech** [dheeraj-2000/dsalgo#86]
I would like to add this topic in the contest section

**Comment by ag41-tech** [comment]
@dheeraj-2000 please assign me this issue

**Comment by dheeraj-2000** [comment]
@ag41-tech Thanks for your suggestion, but I already have a separate repo for hackerrank 30 days of code. Please check and contribute there [Hackerrank-30-days-of-code](https://github.com/dheeraj-2000/30-Days-Of-Code)

Cheers :v:
